### ISSUE TITLE
Any documentation on how to write metadata to a flac file?

### ISSUE THREAD

**Issue by shahriar-shojib** [melchor629/node-flac-bindings#17]
Hello, is there a documentation on how to write track metadata into a flac file using this module or is it out of scope for this project?

**Comment by melchor629** [comment]
Hi! Currently I have no documentation for the API, because this package is just a nice-cool-looking bindings to the C API. But I will try to explain a bit.

Currently there are three metadata APIs in `libFLAC`:

- **level 0**: Reeeaaaallly quick API to read some metadata ([libFLAC documentation](https://xiph.org/flac/api/group__flac__metadata__level0.html)) - only useful if you want to read some blocks of the metadata quick
- **level 1**: basic read-write API for metadata, which reads and writes on each operation ([libFLAC documentation](https://xiph.org/flac/api/group__flac__metadata__level1.html)) - use it to quickly modify the metadata
- **level 2**: advanced read-write API for metadata, which reads everything in memory and then flushes the changes when all changes are done  ([libFLAC documentation](https://xiph.org/flac/api/group__flac__metadata__level2.html)) - advanced usage to make a lot of changes to the file  efficiently

These are mapped in this package as (extracted from the readme):

```javascript
const flac = require('flac-bindings');

// level 0 API
console.log(flac.api.metadata0);

// level 1 API
console.log(flac.api.SimpleIterator);

// level 2 API
console.log(flac.api.Chain);
console.log(flac.api.Iterator);

// metadata objects
console.log(flac.api.metadata);
```

The level 0 contains the 0 functions in it (names are similar, with an IDE that understands TypeScript types you'll get autocomplete suggestions).

The level 1 and level 2 APIs are classes that wraps the behaviour of each object in it. For example, all functions that start with `FLAC__metadata_chain_` are methods inside `flac.api.Iterator` class.

The metadata objects (`VorbisComment`, `Picture`...) can be found inside `flac.api.metadata`;

So now, if you read the libFLAC documentation, you will be able to (more or less) write metadata to files.

You can checkout the tests for some examples of how to use it in JS: [metadata level 1 tests](https://github.com/melchor629/node-flac-bindings/blob/dev/test/metadata1.test.js#L317) and [metadata level 2 tests](https://github.com/melchor629/node-flac-bindings/blob/dev/test/metadata2.test.js#L325).

A quick (but not tested) example:

```javascript
const { api: flac } = require('flac-bindings');

const it = new flac.SimpleIterator();
it.init('path/to/the/file.flac');

// adding a vorbis comment: the ID3-like tags for Ogg and FLAC
// cannot modify the first block which is STREAMINFO, so adding one after it
const vorbisComment = new flac.metadata.VorbisCommentMetadata();
vorbisComment.appendComment('TITLE=Example Song');
vorbisComment.appendComment('ARTIST=Unknown');
it.insertBlockAfter(vorbisComment);

// no need to close anything, it is already written to the file
```

And that's all I think. Hope this helps you start writing metadata to flac files.

I will let this issue open so if you have more questions, just write them on it. If you think this is all you need, feel free to close the issue.

**Comment by shahriar-shojib** [comment]
Thanks , I am now able to add metadata How do I write a picture from a buffer or a file into the flac?
Note that I am only concerned about writing only since the files I will be working with will not contain any metadata or picture.

**Comment by shahriar-shojib** [comment]
I am trying to do it like this, 
`it.init('./file.flac');
const vorbisComment = new flac.metadata.VorbisCommentMetadata();
vorbisComment.appendComment('TITLE=Example Song');
vorbisComment.appendComment('ARTIST=Unknown');
vorbisComment.appendComment('ALBUM=test');
const picture = new flac.metadata.PictureMetadata();
const reader = fs.createReadStream('./picture.jpg');
reader.pipe(picture.data);

reader.on('finish', () => {
	it.insertBlockAfter(vorbisComment);
	it.insertBlockAfter(picture);
});`
by doing it like this I get:
`_stream_readable.js:680
  dest.on('unpipe', onunpipe);
       ^

TypeError: Cannot read property 'on' of null`

**Comment by shahriar-shojib** [comment]
Nevermind, I was able to get this done with **fs.readFile**

```
fs.readFile('./picture.jpg', (err, data) => {
	picture.data = data;
	it.insertBlockAfter(vorbisComment);
	it.insertBlockAfter(picture);
});
```

**Comment by melchor629** [comment]
Cool, I see you managed to modify flac metadata correctly :)

As you can see, the picture metadata expects a buffer and can be read with `fs.readFile` (or `fs.readFileSync`). Also I recommend you to fill the `picture.mimeType` if you don't do it.

Thanks for raising the question, and happy coding :)
