### ISSUE TITLE
When I packaged the Electron project, it didn't work

### ISSUE THREAD

**Issue by zhushenwudi** [melchor629/node-flac-bindings#38]
At present, everything is normal except the interruption problem mentioned in the last issue. We are currently working on packaging. But when I pack, the software crashes when I open it

![QQ截图20220625160518](https://user-images.githubusercontent.com/30340027/175764581-b9a93987-a21a-418f-9480-bf6e9430dc95.png)

And I use "native-ext-loader "to process webpack, it can open, but can not to convert the format.

The first question is whether formal packaging can rely on flac-bindings under the same node_modules as DEV. Or do you need to rely directly on node files.
The second question is, how can my Webpack be configured to run properly if it is referenced directly under node_module? How can I modify my configuration to make it work if It is referenced through a Node file.

There is no detailed description of this aspect in readme. Maybe this is the first case of electron packing, so I may trouble you

**Comment by zhushenwudi** [comment]
![QQ截图20220625160518](https://user-images.githubusercontent.com/30340027/175764851-dbe4e7f5-7bf0-4e9f-ac45-0ff5fd482f40.png)

![QQ截图20220625160518](https://user-images.githubusercontent.com/30340027/175764874-9d576d1e-d98b-4771-86bc-0453e15c1396.png)

![QQ截图20220625160518](https://user-images.githubusercontent.com/30340027/175764914-e6d33e65-5fde-4bf9-9ed9-ff1041367a44.png)

**Comment by zhushenwudi** [comment]
I used Node-loader to make the program open by DEV, but the conversion will give an error

![QQ截图20220625160518](https://user-images.githubusercontent.com/30340027/175765084-2917c754-64d3-4573-952a-11547133682b.png)

**Comment by melchor629** [comment]
Hi again!

Well the native code is just a wrapper from C code to node. The `FileDecoder` and `StreamDecoder` implementations are in .js files inside `lib` folder. Never worked with webpack and native modules so I will try to help as much as I can.

The thing is, you should load the library using the usual `import ... from 'flac-bindings';`, internally uses [bindings](https://github.com/TooTallNate/node-bindings) to load the native code. For what I imagine, the idea is to keep the file inside one of the folders the mentioned library looks for. If you left with the usual import, the `bindings` should fail with a list of paths that tried to read from. In general, the native code is placed in `build/Release/flac-bindings.node` (the relative path is usually where `flac-bindings` is inside a `node_modules` folder).

In your case, because you are bundling the code with webpack, I'm not sure where the `.node` file should be placed. In the `bindings` code, when using webpack, uses the real `require` from nodejs, so maybe the file should be placed in `build/Release/flac-bindings.node` relative to where the electron app runs. But not sure.

Now, looking at your first screenshot, the `getFileName` function looks like it is from [here](https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L147). It seems that this function fails for some reason on your side. So looking at the `bindings` code, there is a way to avoid calling this function (I think).

With all this quick investigation, first I will update my native load code so it does not call to that `getFileName` function and then I will release the new version. I will come back to the issue when the release is ready, with some ideas I will come up to investigate this.

Thanks for raising the issue and your work on this lately :)

**Comment by zhushenwudi** [comment]
Yes, I refer to many mature third-party libraries, which seem to be loaded in the production environment  "/resources" directory (win) or "/Resource" directory (MAC, Linux)

```json
{
    test: /\.node$/,
    loader: "native-ext-loader",
    options: {
        rewritePath: targetPlatform == 'win32' ? '../resources' : '../Resources'
    }
}
```

And copy the node file to the packaging directory in the following way

```json
"win": {
      "target": [
          "nsis"
      ],
      "extraFiles": [
          {
              "from": "node_modules/flac-bindings/build/Release/flac-bindings.node",
              "to": "./resources"
          }
      ]
  },
```

I have referred to this part of the code and added it to the project, but now I may be worried that your library should specify to run the files under a certain directory. I guess it should be like this. Of course, I don't know much about it here, but just speak freely

**Comment by melchor629** [comment]
Well that may work, that's a new area for me as well :/

When possible, try using the new version in which I changed a bit how the native code is loaded, and see if it loads or fails (and what is the error now).

**Comment by zhushenwudi** [comment]
OK, I'll be looking forward to it

**Comment by zhushenwudi** [comment]
That is great! The new version can be packaged and work properly. Thank you for your timely reply and code correction. Thank you very much!

There's another little question. Where are the generated node files of different platforms saved? Can I copy them directly?

**Comment by melchor629** [comment]
Glad to hear it can be packed in Electron, and works fine now! Thanks to you for rising the issue and help me improve the library :)
